# Generated by Django 4.1.5 on 2023-02-03 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPttnCode',
            fields=[
                ('adminPttnCd', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('adminPttnNm', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='LongTermAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longTermAdminSym', models.CharField(max_length=11)),
                ('adminPttnCd', models.CharField(max_length=3)),
                ('siDoCd', models.CharField(max_length=2)),
                ('siGunGuCd', models.CharField(max_length=3)),
                ('adminNm', models.CharField(max_length=100)),
                ('ratingCd', models.CharField(blank=True, max_length=15, null=True)),
                ('ratingDate', models.DateField()),
                ('ratingGrade', models.CharField(max_length=1)),
                ('detailAddr', models.CharField(max_length=1000)),
                ('telNo', models.CharField(max_length=18)),
                ('jaehwalCd', models.CharField(blank=True, max_length=1, null=True)),
                ('chimaeCd', models.CharField(blank=True, max_length=1, null=True)),
                ('photo', models.ImageField(null=True, upload_to='images/')),
                ('longTermPeribRgtDt', models.DateField()),
                ('stpRptDt', models.DateField()),
                ('adminCd', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memberId', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('registerDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewId', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('amKind', models.PositiveSmallIntegerField(default=0)),
                ('faClean', models.PositiveSmallIntegerField(default=0)),
                ('content', models.CharField(blank=True, max_length=500)),
                ('createDate', models.DateField()),
                ('modifyDate', models.DateField(blank=True, null=True)),
                ('memberId', models.PositiveSmallIntegerField()),
                ('longTermAdminSym', models.CharField(max_length=11)),
                ('adminPttnCd', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SiDoGunGuCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siDoCd', models.CharField(max_length=2)),
                ('siGunGuCd', models.CharField(max_length=3)),
                ('siDoNm', models.CharField(max_length=20)),
                ('siGunGuNm', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddIndex(
            model_name='sidogungucode',
            index=models.Index(fields=['siDoCd', 'siGunGuCd'], name='PK_siDoGunGuCode'),
        ),
        migrations.AlterUniqueTogether(
            name='sidogungucode',
            unique_together={('siDoCd', 'siGunGuCd')},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['memberId'], name='FK_Member_Review'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['longTermAdminSym', 'adminPttnCd'], name='FK_LongTermAdmin_Review'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('longTermAdminSym', 'adminPttnCd')},
        ),
        migrations.AddField(
            model_name='longtermadmin',
            name='adminpttncode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.adminpttncode'),
        ),
        migrations.AddField(
            model_name='longtermadmin',
            name='sidogungucode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.sidogungucode'),
        ),
        migrations.AddIndex(
            model_name='adminpttncode',
            index=models.Index(fields=['adminPttnCd'], name='PK_adminPttnCode'),
        ),
        migrations.AlterUniqueTogether(
            name='adminpttncode',
            unique_together={('adminPttnCd',)},
        ),
        migrations.AddIndex(
            model_name='longtermadmin',
            index=models.Index(fields=['adminPttnCd'], name='FK_adminPttnCode_LongTermAdmin'),
        ),
        migrations.AddIndex(
            model_name='longtermadmin',
            index=models.Index(fields=['siDoCd', 'siGunGuCd'], name='FK_siDoGunGuCode_LongTermAdmin'),
        ),
        migrations.AlterUniqueTogether(
            name='longtermadmin',
            unique_together={('longTermAdminSym', 'adminPttnCd')},
        ),
    ]
