# Generated by Django 4.1.5 on 2023-02-05 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPttnCode',
            fields=[
                ('adminPttnCd', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('adminPttnNm', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='LongTermAdmin',
            fields=[
                ('longtermadminId', models.IntegerField(primary_key=True, serialize=False)),
                ('longTermAdminSym', models.CharField(max_length=11)),
                ('adminPttnCd', models.CharField(max_length=3)),
                ('siDoCd', models.CharField(max_length=2)),
                ('siGunGuCd', models.CharField(max_length=3)),
                ('adminNm', models.CharField(max_length=100)),
                ('ratingCd', models.CharField(blank=True, max_length=15, null=True)),
                ('ratingDate', models.DateField()),
                ('ratingGrade', models.CharField(max_length=1)),
                ('detailAddr', models.CharField(max_length=1000)),
                ('telNo', models.CharField(max_length=18)),
                ('jaehwalCd', models.CharField(blank=True, max_length=1, null=True)),
                ('chimaeCd', models.CharField(blank=True, max_length=1, null=True)),
                ('photo', models.ImageField(null=True, upload_to='images/')),
                ('longTermPeribRgtDt', models.DateField()),
                ('stpRptDt', models.DateField()),
                ('adminCd', models.CharField(max_length=1)),
                ('adminpttncode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.adminpttncode')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memberId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('registerDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SiDoGunGuCode',
            fields=[
                ('siDoGunGuCd', models.IntegerField(primary_key=True, serialize=False)),
                ('siDoCd', models.CharField(max_length=2)),
                ('siGunGuCd', models.CharField(max_length=3)),
                ('siDoNm', models.CharField(max_length=20)),
                ('siGunGuNm', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewId', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('amKind', models.SmallIntegerField(default=0)),
                ('faClean', models.SmallIntegerField(default=0)),
                ('content', models.CharField(blank=True, max_length=500)),
                ('createDate', models.DateField()),
                ('modifyDate', models.DateField(blank=True, null=True)),
                ('longtermadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.longtermadmin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='longtermadmin',
            name='sidogungucode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.sidogungucode'),
        ),
    ]
