# Generated by Django 4.1.5 on 2023-02-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_rename_longtermadminid_longtermadmin_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='createDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='modifyDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
