# Generated by Django 4.1.5 on 2023-02-03 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AceptncNmprDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longTermAdminSym', models.CharField(max_length=11)),
                ('adminPttnCd', models.CharField(max_length=3)),
                ('totPer', models.SmallIntegerField(null=True)),
                ('maNowPer', models.SmallIntegerField(null=True)),
                ('fmNowPer', models.SmallIntegerField(null=True)),
                ('maRsvPer', models.SmallIntegerField(null=True)),
                ('fmRsvPer', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminPttnCode',
            fields=[
                ('adminPttnCd', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('adminPttnNm', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSttusDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longTermAdminSym', models.CharField(max_length=11)),
                ('adminPttnCd', models.CharField(max_length=3)),
                ('adminNm', models.CharField(max_length=100)),
                ('hmPostNo', models.CharField(max_length=6, null=True)),
                ('siDoCd', models.CharField(max_length=2)),
                ('siGunGuCd', models.CharField(max_length=3)),
                ('HDongCd', models.CharField(max_length=3, null=True)),
                ('BDongCd', models.CharField(max_length=3, null=True)),
                ('riCd', models.CharField(max_length=2, null=True)),
                ('detailAddr', models.CharField(max_length=1000, null=True)),
                ('roadNmCd', models.CharField(max_length=12, null=True)),
                ('gunmulMlno', models.CharField(max_length=5, null=True)),
                ('gunmulSlno', models.CharField(max_length=5, null=True)),
                ('fl', models.CharField(max_length=10, null=True)),
                ('locTelNo_1', models.CharField(max_length=4, null=True)),
                ('locTelNo_2', models.CharField(max_length=4, null=True)),
                ('locTelNo_3', models.CharField(max_length=10, null=True)),
                ('longTermPeribRgtDt', models.DateField()),
                ('StpRptDt', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InsttEtcDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longTermAdminSym', models.CharField(max_length=11)),
                ('adminPttnCd', models.CharField(max_length=3)),
                ('hmpgAddr', models.CharField(blank=True, max_length=500, null=True)),
                ('tfMth', models.CharField(max_length=2000)),
                ('pkngEquip', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='InsttSttusDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longTermAdminSym', models.CharField(max_length=11)),
                ('adminPttnCd', models.CharField(max_length=3)),
                ('prsnRoomReal1', models.SmallIntegerField(default=0)),
                ('prsnRoomReal2', models.SmallIntegerField(default=0)),
                ('prsnRoomReal3', models.SmallIntegerField(default=0)),
                ('prsnRoomReal4', models.SmallIntegerField(default=0)),
                ('spcAcupRoomReal', models.SmallIntegerField(default=0)),
                ('ofce', models.SmallIntegerField(default=0)),
                ('medRoomReal', models.SmallIntegerField(default=0)),
                ('funcTrnRoomReal', models.SmallIntegerField(default=0)),
                ('pgmRoomReal', models.SmallIntegerField(default=0)),
                ('crmnyPrst', models.SmallIntegerField(default=0)),
                ('batRoom', models.SmallIntegerField(default=0)),
                ('taxPageLong', models.SmallIntegerField(default=0)),
                ('taxRoom', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LongTermAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longTermAdminSym', models.CharField(max_length=11)),
                ('adminPttnCd', models.CharField(max_length=3)),
                ('siDoCd', models.CharField(max_length=2)),
                ('siGunGuCd', models.CharField(max_length=3)),
                ('adminNm', models.CharField(max_length=100)),
                ('ratingCd', models.CharField(blank=True, max_length=15, null=True)),
                ('ratingDate', models.DateField()),
                ('ratingGrade', models.CharField(max_length=1)),
                ('detailAddr', models.CharField(max_length=1000)),
                ('telNo', models.CharField(max_length=18)),
                ('jaehwalCd', models.CharField(blank=True, max_length=1, null=True)),
                ('chimaeCd', models.CharField(blank=True, max_length=1, null=True)),
                ('photo', models.ImageField(null=True, upload_to='images/')),
                ('longTermPeribRgtDt', models.DateField()),
                ('stpRptDt', models.DateField()),
                ('adminCd', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='LongTermAdminRating',
            fields=[
                ('no', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('ratingCd', models.CharField(blank=True, max_length=15, null=True)),
                ('longTermAdminCd', models.CharField(blank=True, max_length=13, null=True)),
                ('longTermAdminNm', models.CharField(blank=True, max_length=100, null=True)),
                ('adminPttnName', models.CharField(blank=True, max_length=20, null=True)),
                ('siDoName', models.CharField(blank=True, max_length=20, null=True)),
                ('siGunGuName', models.CharField(blank=True, max_length=20, null=True)),
                ('ratingDate', models.DateField(blank=True, null=True)),
                ('ratingGrade', models.CharField(blank=True, max_length=1, null=True)),
                ('opRating', models.SmallIntegerField(blank=True, null=True)),
                ('safeRating', models.SmallIntegerField(blank=True, null=True)),
                ('rightRating', models.SmallIntegerField(blank=True, null=True)),
                ('processRating', models.SmallIntegerField(blank=True, null=True)),
                ('resultRating', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiDoGunGuCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siDoCd', models.CharField(max_length=2)),
                ('siGunGuCd', models.CharField(max_length=3)),
                ('siDoNm', models.CharField(max_length=20)),
                ('siGunGuNm', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddIndex(
            model_name='sidogungucode',
            index=models.Index(fields=['siDoCd', 'siGunGuCd'], name='PK_siDoGunGuCode'),
        ),
        migrations.AlterUniqueTogether(
            name='sidogungucode',
            unique_together={('siDoCd', 'siGunGuCd')},
        ),
        migrations.AddField(
            model_name='longtermadmin',
            name='adminpttncode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.adminpttncode'),
        ),
        migrations.AddField(
            model_name='longtermadmin',
            name='sidogungucode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.sidogungucode'),
        ),
        migrations.AddField(
            model_name='insttsttusdetail',
            name='longtermadmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.longtermadmin'),
        ),
        migrations.AddField(
            model_name='insttetcdetail',
            name='longtermadmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.longtermadmin'),
        ),
        migrations.AddField(
            model_name='generalsttusdetail',
            name='longtermadmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.longtermadmin'),
        ),
        migrations.AddIndex(
            model_name='adminpttncode',
            index=models.Index(fields=['adminPttnCd'], name='PK_adminPttnCode'),
        ),
        migrations.AlterUniqueTogether(
            name='adminpttncode',
            unique_together={('adminPttnCd',)},
        ),
        migrations.AddField(
            model_name='aceptncnmprdetail',
            name='longtermadmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care.longtermadmin'),
        ),
        migrations.AddIndex(
            model_name='longtermadmin',
            index=models.Index(fields=['adminPttnCd'], name='FK_adminPttnCode_LongTermAdmin'),
        ),
        migrations.AddIndex(
            model_name='longtermadmin',
            index=models.Index(fields=['siDoCd', 'siGunGuCd'], name='FK_siDoGunGuCode_LongTermAdmin'),
        ),
        migrations.AlterUniqueTogether(
            name='longtermadmin',
            unique_together={('longTermAdminSym', 'adminPttnCd')},
        ),
        migrations.AddIndex(
            model_name='insttsttusdetail',
            index=models.Index(fields=['longTermAdminSym', 'adminPttnCd'], name='FK_LongTermAdmin_InsttSttusD'),
        ),
        migrations.AlterUniqueTogether(
            name='insttsttusdetail',
            unique_together={('longTermAdminSym', 'adminPttnCd')},
        ),
        migrations.AddIndex(
            model_name='insttetcdetail',
            index=models.Index(fields=['longTermAdminSym', 'adminPttnCd'], name='FK_LongTermAdmin_InsttEtcD'),
        ),
        migrations.AlterUniqueTogether(
            name='insttetcdetail',
            unique_together={('longTermAdminSym', 'adminPttnCd')},
        ),
        migrations.AddIndex(
            model_name='generalsttusdetail',
            index=models.Index(fields=['longTermAdminSym', 'adminPttnCd'], name='FK_LongTermAdmin_GeneralSttusD'),
        ),
        migrations.AlterUniqueTogether(
            name='generalsttusdetail',
            unique_together={('longTermAdminSym', 'adminPttnCd')},
        ),
        migrations.AddIndex(
            model_name='aceptncnmprdetail',
            index=models.Index(fields=['longTermAdminSym', 'adminPttnCd'], name='FK_LongTermAdmin_AceptncNmprD'),
        ),
        migrations.AlterUniqueTogether(
            name='aceptncnmprdetail',
            unique_together={('longTermAdminSym', 'adminPttnCd')},
        ),
    ]
